stages:
  - install
  - build

variables:
  NODE_VERSION: "18"

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

before_script:
  - apt-get update -qq && apt-get install -y curl
  - curl -fsSL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
  - apt-get install -y nodejs

# 安裝前端
client_install:
  stage: install
  script:
    - cd client
    - npm install
  artifacts:
    paths:
      - client/node_modules/

# 部署前端
client_deploy:
  stage: build
  script:
    - cd client
    - npm run build
  artifacts:
    paths:
      - client/dist/

# 安裝後端
server_install:
  stage: install
  script:
    - cd server
    - npm install
    - npm install nodemon --save-dev 
  artifacts:
    paths:
      - server/node_modules/

# 部署後端
server_deploy:
  stage: deploy
  script:
  script:
    - cd server
    - npm install --production   # 安裝生產環境的依賴
    - nohup npm run start &       # 在背景運行 nodemon 來啟動後端伺服器
  only:
    - main